# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Suppliers.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1430, 900)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(390, 190, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_4.setObjectName("label_4")
        self.polosa2_2 = QtWidgets.QLabel(Form)
        self.polosa2_2.setGeometry(QtCore.QRect(-50, 150, 1621, 20))
        self.polosa2_2.setObjectName("polosa2_2")
        self.pushButtonDob_Sup = QtWidgets.QPushButton(Form)
        self.pushButtonDob_Sup.setGeometry(QtCore.QRect(900, 110, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButtonDob_Sup.setFont(font)
        self.pushButtonDob_Sup.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border-radius: 11px;\n"
"    border: 2px solid black;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 192, 203, 100); /* Прозрачно розовый */\n"
"}")
        self.pushButtonDob_Sup.setObjectName("pushButtonDob_Sup")
        self.pushButtonSapp1 = QtWidgets.QPushButton(Form)
        self.pushButtonSapp1.setGeometry(QtCore.QRect(380, 20, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButtonSapp1.setFont(font)
        self.pushButtonSapp1.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border-radius: 11px;\n"
"    border: 2px solid black;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 192, 203, 100); /* Прозрачно розовый */\n"
"}")
        self.pushButtonSapp1.setObjectName("pushButtonSapp1")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(1060, 190, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_8.setObjectName("label_8")
        self.pushButtonSale1 = QtWidgets.QPushButton(Form)
        self.pushButtonSale1.setGeometry(QtCore.QRect(710, 20, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButtonSale1.setFont(font)
        self.pushButtonSale1.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border-radius: 11px;\n"
"    border: 2px solid black;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 192, 203, 100); /* Прозрачно розовый */\n"
"}")
        self.pushButtonSale1.setObjectName("pushButtonSale1")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(60, 190, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_2.setObjectName("label_2")
        self.pushButtonIzmen_Sapp = QtWidgets.QPushButton(Form)
        self.pushButtonIzmen_Sapp.setGeometry(QtCore.QRect(1100, 110, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButtonIzmen_Sapp.setFont(font)
        self.pushButtonIzmen_Sapp.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border-radius: 11px;\n"
"    border: 2px solid black;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 192, 203, 100); /* Прозрачно розовый */\n"
"}")
        self.pushButtonIzmen_Sapp.setObjectName("pushButtonIzmen_Sapp")
        self.Fon = QtWidgets.QLabel(Form)
        self.Fon.setGeometry(QtCore.QRect(-4, -8, 1431, 911))
        self.Fon.setText("")
        self.Fon.setPixmap(QtGui.QPixmap("fonn.png"))
        self.Fon.setObjectName("Fon")
        self.polosa2 = QtWidgets.QLabel(Form)
        self.polosa2.setGeometry(QtCore.QRect(-60, 70, 1621, 20))
        self.polosa2.setObjectName("polosa2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 100, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButtonGlavnaya = QtWidgets.QPushButton(Form)
        self.pushButtonGlavnaya.setGeometry(QtCore.QRect(30, 20, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonGlavnaya.setFont(font)
        self.pushButtonGlavnaya.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border-radius: 11px;\n"
"    border: 2px solid black;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 192, 203, 100); /* Прозрачно розовый */\n"
"}")
        self.pushButtonGlavnaya.setObjectName("pushButtonGlavnaya")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(820, 190, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_5.setObjectName("label_5")
        self.pushButtonOtchet = QtWidgets.QPushButton(Form)
        self.pushButtonOtchet.setGeometry(QtCore.QRect(1070, 20, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButtonOtchet.setFont(font)
        self.pushButtonOtchet.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border-radius: 11px;\n"
"    border: 2px solid black;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 192, 203, 100); /* Прозрачно розовый */\n"
"}")
        self.pushButtonOtchet.setObjectName("pushButtonOtchet")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(50, 260, 1270, 411))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.Fon.raise_()
        self.pushButtonGlavnaya.raise_()
        self.pushButtonOtchet.raise_()
        self.pushButtonSale1.raise_()
        self.label_4.raise_()
        self.pushButtonSapp1.raise_()
        self.label.raise_()
        self.pushButtonIzmen_Sapp.raise_()
        self.label_8.raise_()
        self.label_2.raise_()
        self.polosa2.raise_()
        self.polosa2_2.raise_()
        self.pushButtonDob_Sup.raise_()
        self.label_5.raise_()
        self.tableWidget.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Наименование"))
        self.polosa2_2.setText(_translate("Form", "___________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________"))
        self.pushButtonDob_Sup.setText(_translate("Form", "Добавить"))
        self.pushButtonSapp1.setText(_translate("Form", "Поставщики"))
        self.label_8.setText(_translate("Form", "Контактная информация"))
        self.pushButtonSale1.setText(_translate("Form", "Продажи"))
        self.label_2.setText(_translate("Form", "ФИО"))
        self.pushButtonIzmen_Sapp.setText(_translate("Form", "Изменить"))
        self.polosa2.setText(_translate("Form", "___________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________"))
        self.label.setText(_translate("Form", "Поставщики"))
        self.pushButtonGlavnaya.setText(_translate("Form", "Товары"))
        self.label_5.setText(_translate("Form", "Товары"))
        self.pushButtonOtchet.setText(_translate("Form", "Отчеты"))
